=== Bim4Everyone/RevitPlugins/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "BundleName": {
          "type": "string",
          "description": "Bundle name"
        },
        "BundleOutput": {
          "type": "string",
          "description": "Bundle output"
        },
        "BundleType": {
          "type": "string",
          "description": "Bundle type",
          "enum": [
            "InvokeButton",
            "PushButton"
          ]
        },
        "Configuration": {
          "type": "string",
          "description": "Configuration to build. Default is 'Debug' (local) or 'Release' (server)",
          "enum": [
            "Debug",
            "Release"
          ]
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "ExtensionsAppToken": {
          "type": "string",
          "description": "Extensions token value",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "IconUrl": {
          "type": "string",
          "description": "Bundle icon url"
        },
        "MaxVersion": {
          "type": "string",
          "description": "Max Revit version. Default value is \"Rv2024\"",
          "enum": [
            "Rv2016",
            "Rv2017",
            "Rv2018",
            "Rv2019",
            "Rv2020",
            "Rv2021",
            "Rv2022",
            "Rv2023",
            "Rv2024"
          ]
        },
        "MinVersion": {
          "type": "string",
          "description": "Min Revit version. Default value is \"Rv2022\"",
          "enum": [
            "Rv2016",
            "Rv2017",
            "Rv2018",
            "Rv2019",
            "Rv2020",
            "Rv2021",
            "Rv2022",
            "Rv2023",
            "Rv2024"
          ]
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "Output": {
          "type": "string",
          "description": "Output directory"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "PluginName": {
          "type": "string",
          "description": "Project (plugin) name in solution"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "PublishDirectory": {
          "type": "string",
          "description": "Publish directory"
        },
        "PullRequestMerged": {
          "type": "boolean",
          "description": "When PullRequest has merged equals true"
        },
        "RevitPluginsAppToken": {
          "type": "string",
          "description": "RevitPlugins token value",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "RevitVersions": {
          "type": "array",
          "description": "Build Revit versions. Default value is Empty",
          "items": {
            "type": "string",
            "enum": [
              "Rv2016",
              "Rv2017",
              "Rv2018",
              "Rv2019",
              "Rv2020",
              "Rv2021",
              "Rv2022",
              "Rv2023",
              "Rv2024"
            ]
          }
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "CloneRepos",
              "Compile",
              "CreateBranch",
              "CreateBundle",
              "CreatePlugin",
              "CreateProfile",
              "CreatePullRequest",
              "CreateWorkflow",
              "FullClean",
              "Publish",
              "PublishArtifacts"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "CloneRepos",
              "Compile",
              "CreateBranch",
              "CreateBundle",
              "CreatePlugin",
              "CreateProfile",
              "CreatePullRequest",
              "CreateWorkflow",
              "FullClean",
              "Publish",
              "PublishArtifacts"
            ]
          }
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitMarkAllDocuments.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitMarkAllDocuments",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/22177/add-tag",
  "BundleName": "Маркировать всё",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Данные.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitKrChecker.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitKrChecker",
  "PublishDirectory": "03.KR.extension\\КР.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/LunGMFAtVtVk/financial-growth-analysis",
  "BundleName": "Проверить модель",
  "BundleType": "InvokeButton",
  "BundleOutput": "03.KR.extension\\КР.tab\\ВОР.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitFamilyParameterAdder.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.sln",
  "PluginName": "RevitFamilyParameterAdder",
  "PublishDirectory": "03.KR.extension\\КР.tab\\bin",
  "IconUrl": "https://icons8.com/icon/iyK9ZX69nYUU/insert-row",
  "BundleName": "Добавить параметры в семейство",
  "BundleType": "InvokeButton",
  "BundleOutput": "03.KR.extension\\КР.tab\\Параметры.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitSplitMepCurve.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitSplitMepCurve",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/22945/cut-paper",
  "BundleName": "Разделить по уровню СМР",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\СМР.panel\\СМР.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitSuperfilter.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.sln",
  "PluginName": "RevitSuperfilter",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "IconUrl": "",
  "BundleName": "Суперфильтр",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Выборка.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitBuildCoordVolumes.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitBuildCoordVolumes",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/pOOiCxeiUk4q/element-level",
  "BundleName": "Построить объемы СМР",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\СМР.panel\\СМР.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitMechanicalSpecification.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitMechanicalSpecification",
  "PublishDirectory": "04.OV-VK.extension\\ОВиВК.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.ru/icon/gAUDhWVcYLgj/list-of-specification-of-engineering-material-guide-template-format",
  "BundleName": "Обновить спецификацию",
  "BundleType": "InvokeButton",
  "BundleOutput": "04.OV-VK.extension\\ОВиВК.tab\\Спецификация Test.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitRoomTagPlacement.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.sln",
  "PluginName": "RevitRoomTagPlacement",
  "PublishDirectory": "02.AR.extension\\АР.tab\\bin",
  "IconUrl": "https://icons8.com/icon/22177/add-tag",
  "BundleName": "Маркировать помещения",
  "BundleType": "InvokeButton",
  "BundleOutput": "02.AR.extension\\АР.tab\\Квартирография.panel\\Помещения.pulldown"
}
