=== Bim4Everyone/RevitPlugins/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "BundleName": {
          "type": "string",
          "description": "Bundle name"
        },
        "BundleOutput": {
          "type": "string",
          "description": "Bundle output"
        },
        "BundleType": {
          "type": "string",
          "description": "Bundle type",
          "enum": [
            "InvokeButton",
            "PushButton"
          ]
        },
        "Configuration": {
          "type": "string",
          "description": "Configuration to build. Default is 'Debug' (local) or 'Release' (server)",
          "enum": [
            "Debug",
            "Release"
          ]
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "ExtensionsAppToken": {
          "type": "string",
          "description": "Extensions token value",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "IconUrl": {
          "type": "string",
          "description": "Bundle icon url"
        },
        "MaxVersion": {
          "type": "string",
          "description": "Max Revit version. Default value is \"Rv2024\"",
          "enum": [
            "Rv2016",
            "Rv2017",
            "Rv2018",
            "Rv2019",
            "Rv2020",
            "Rv2021",
            "Rv2022",
            "Rv2023",
            "Rv2024"
          ]
        },
        "MinVersion": {
          "type": "string",
          "description": "Min Revit version. Default value is \"Rv2022\"",
          "enum": [
            "Rv2016",
            "Rv2017",
            "Rv2018",
            "Rv2019",
            "Rv2020",
            "Rv2021",
            "Rv2022",
            "Rv2023",
            "Rv2024"
          ]
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "Output": {
          "type": "string",
          "description": "Output directory"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "PluginName": {
          "type": "string",
          "description": "Project (plugin) name in solution"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "PublishDirectory": {
          "type": "string",
          "description": "Publish directory"
        },
        "PullRequestMerged": {
          "type": "boolean",
          "description": "When PullRequest has merged equals true"
        },
        "RevitPluginsAppToken": {
          "type": "string",
          "description": "RevitPlugins token value",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "RevitVersions": {
          "type": "array",
          "description": "Build Revit versions. Default value is Empty",
          "items": {
            "type": "string",
            "enum": [
              "Rv2016",
              "Rv2017",
              "Rv2018",
              "Rv2019",
              "Rv2020",
              "Rv2021",
              "Rv2022",
              "Rv2023",
              "Rv2024"
            ]
          }
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "CloneRepos",
              "Compile",
              "CreateBranch",
              "CreateBundle",
              "CreatePlugin",
              "CreateProfile",
              "CreatePullRequest",
              "CreateWorkflow",
              "FullClean",
              "Publish",
              "PublishArtifacts"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "CloneRepos",
              "Compile",
              "CreateBranch",
              "CreateBundle",
              "CreatePlugin",
              "CreateProfile",
              "CreatePullRequest",
              "CreateWorkflow",
              "FullClean",
              "Publish",
              "PublishArtifacts"
            ]
          }
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitRefreshLinks.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitRefreshLinks",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/16013/broken-link",
  "BundleName": "Обновить связанные файлы",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Связи.panel\\Связи rvt.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitMirroredElements.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitMirroredElements",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/15046/invert-selection",
  "BundleName": "Проверка на зеркальность",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Проверки.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitRoomAnnotations.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitRoomAnnotations",
  "PublishDirectory": "05.EOM-SS.extension\\ЭОМ и СС.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "hhttps://icons8.com/icon/4025/room",
  "BundleName": "Помещения в ЭОМ",
  "BundleType": "InvokeButton",
  "BundleOutput": "05.EOM-SS.extension\\ЭОМ и СС.tab\\Помещения в ЭОМ.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitParamsChecker.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitParamsChecker",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/21964/true-false",
  "BundleName": "Проверка параметров",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Проверки.panel"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitValueModifier.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitValueModifier",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/set/copy/windows",
  "BundleName": "Перенос параметров",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\Данные.panel\\Перенос параметров.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitUnmodelingMep.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.slnx",
  "PluginName": "RevitUnmodelingMep",
  "PublishDirectory": "04.OV-VK.extension\\ОВиВК.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/22177/add-tag",
  "BundleName": "Настройки немоделируемых",
  "BundleType": "InvokeButton",
  "BundleOutput": "04.OV-VK.extension\\ОВиВК.tab\\Спецификации.panel\\Дополнительные.stack\\Немоделируемые.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitIsolateByParameter.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.sln",
  "PluginName": "RevitIsolateByParameter",
  "PublishDirectory": "01.BIM.extension\\BIM.tab\\bin",
  "IconUrl": "https://icons8.com/icon/41532/3d-glasses",
  "BundleName": "Изолировать по параметру",
  "BundleType": "InvokeButton",
  "BundleOutput": "01.BIM.extension\\BIM.tab\\СМР.panel\\СМР.pulldown"
}

=== Bim4Everyone/RevitPlugins/.nuke/parameters.RevitMarkingPiles.json
{
  "$schema": "./build.schema.json",
  "Solution": "RevitPlugins.sln",
  "PluginName": "RevitMarkingPiles",
  "PublishDirectory": "03.KR.extension\\КР.tab\\bin",
  "RevitVersions": [
    "Rv2022",
    "Rv2023",
    "Rv2024"
  ],
  "IconUrl": "https://icons8.com/icon/59856/pencil",
  "BundleName": "Маркировка свай",
  "BundleType": "PushButton",
  "BundleOutput": "03.KR.extension\\КР.tab\\Документация.panel\\Маркировка Свай"
}
